Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [ ]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
import numpy as np
c = np.random.rand(3, 4)
print(c)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
d = np.zeros((3, 4))
print(d)

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
e = np.ones((3, 4))
print(e)

[[0.12818556 0.66711197 0.26679378 0.87641088]
 [0.58483888 0.5286467  0.47089443 0.37302385]
 [0.37081727 0.01576059 0.77425926 0.18523188]]


In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
import numpy as np
def create_array(start, end, steps):
    return np.linspace(start, end, steps)
print(create_array(0, 10, 6))

[ 0.  2.  4.  6.  8. 10.]


### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
import numpy as np
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
def add(a, b):
    return a + b
def subtract(a, b):
    return a - b
def multiply(a, b):
    return a * b
def divide(a, b):
    return a / b

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
import numpy as np
def sum_along_axis(a, axis):
    return np.sum(a, axis=axis)
print(sum_along_axis(a, 0))

# Write a NumPy function to get the sum of the array 'a' along axis=1
print(sum_along_axis(a, 1))

[ 6 17 14]


In [ ]:
# Write a NumPy function to reverse the array 'a'
import numpy as np
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
def reverse_array(a):
    return np.flip(a)
print(reverse_array(a))

# Write a NumPy function to reverse the array 'a' along axis=0
print(reverse_array(np.flip(a, axis=0)))

# Write a NumPy function to reverse the array 'a' along axis=1
print(reverse_array(np.flip(a,axis=1)))

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'
import numpy as np
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
def sort_array(a):
    return np.sort(a)
print(sort_array(a))

# Write a NumPy function to sort the array 'a' along axis=0
print(sort_array(np.sort(a, axis=0)))

# Write a NumPy function to sort the array 'a' along axis=1
print(sort_array(np.sort(a, axis=1)))

# Write a NumPy function to sort the array 'a' in descending order along axis=0
print(sort_array(np.sort(a, axis=0))[::-1])


[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  1  3]
 [ 1  5  6]
 [ 8  8  9]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 8  8  9]
 [ 1  5  6]
 [-4  1  3]]


In [ ]:
# Write a NumPy function to argsort the array along axis=0
import numpy as np
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
def argsort_array(a):
    return np.argsort(a)
print(argsort_array(np.argsort(a,axis=0)))

# Write a NumPy function to argsort the array along axis=1
print(argsort_array(np.argsort(a,axis=1)))


[[0 1 2]
 [1 0 2]
 [2 0 1]]


In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
import numpy as np
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
def concatenate_arrays(a, b):
    return np.concatenate((a, b), axis=0)
print(concatenate_arrays(a, b))

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
print(np.concatenate((a, b), axis=1))

# Note: You can do the same function using stacking, discover and try that :)


[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8 11 16 18]
 [ 9  3  1 90 37 81]
 [ 1  8  5 61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
import numpy as np
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])
def get_dimensions(a):
    return a.ndim
print(get_dimensions(a))

# Write a NumPy function to get the Shape of the array
def get_shape(a):
    return a.shape
print(get_shape(a))

# Write a NumPy function to get the Size of the array
def get_size(a):
    return a.size
print(get_size(a))


2


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
import numpy as np
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])
def reshape_array(a):
    return a.reshape(1,9)
print(reshape_array(a))

[[4 6 8 9 3 1 1 8 5]]


In [ ]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
import numpy as np
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])
def add_new_axis(a):
    return np.expand_dims(a, axis=0)
print(add_new_axis(a))


[[[4 6 8]
  [9 3 1]
  [1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [46]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
import numpy as np
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
def index_array(a):
    return a[1,2]
print(index_array(a))
a=([4,6,0], [0, 3, 1], [1, 8, 5])
print(tuple(a[1]))
print(a[1:3])



1
(0, 3, 1)
([0, 3, 1], [1, 8, 5])


In [48]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
import numpy as np
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
def select_values(a):
    return a[a>4]
print(select_values(a))

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
print(select_values(a[(a>4) & (a%2==0)]))


[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [49]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [60]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
import numpy as np
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
def inc1(a) :
  b=a.copy()
  return b+np.ones((3,3))
print(inc1(a))



[[5. 7. 1.]
 [1. 4. 2.]
 [2. 9. 6.]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [61]:
# Write a Pandas function to drop rows that contain a missing value.
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
def drop_missing_values(iris_2d):
    return iris_2d[~np.isnan(iris_2d).any(axis=1)]
print(drop_missing_values(iris_2d))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
def find_correlation(iris_2d):
    return np.corrcoef(iris_2d[:, 0], iris_2d[:, 1])[0, 1]
print(find_correlation(iris_2d))

In [62]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
def find_stats(iris_2d):
    return np.mean(iris_2d[:, 2]), np.median(iris_2d[:, 2]), np.std(iris_2d[:, 2])
print(find_stats(iris_2d))

(np.float64(3.758666666666666), np.float64(4.35), np.float64(1.7585291834055212))


In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [68]:
import numpy as np
x = np.arange(4, dtype=np.int64)
print(np.ones_like(x))

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [63]:
import numpy as np
x = np.arange(1, 10)
print(np.split(x, [4, 6]))

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [69]:
import numpy as np
x = np.random.randint(0, 10, (2, 5))
max_values = np.max(x, axis=1)
min_values = np.min(x, axis=1)
max_indices = np.argmax(x, axis=1)
min_indices = np.argmin(x, axis=1)

### Pandas

Run the following load command and solve the following questions

In [70]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [73]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
def count_unique_species(iris_data):
    import pandas as pd
    df = pd.DataFrame(iris_data, columns=names)
    return df['species'].value_counts()
print(count_unique_species(iris_data=iris))

species
b'Iris-setosa'        50
b'Iris-versicolor'    50
b'Iris-virginica'     50
Name: count, dtype: int64


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [75]:
import numpy as np
import pandas as pd
def bin_petal_length(iris_2d):
  petal_lengths = iris_2d[:, 2]
  bins = pd.cut(petal_lengths, bins=[-np.inf, 3, 5, np.inf], labels=['small', 'medium', 'large'])
  return bins

binned_petal_lengths = bin_petal_length(iris_2d)
binned_petal_lengths

['small', 'small', 'small', 'small', 'small', ..., 'large', 'medium', 'large', 'large', 'large']
Length: 150
Categories (3, object): ['small' < 'medium' < 'large']

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [76]:
import numpy as np
import pandas as pd

def most_frequent_petal_length(iris_data):
  df = pd.DataFrame(iris_data, columns=names)
  return df['petallength'].value_counts().index[0]

most_frequent_value = most_frequent_petal_length(iris)
most_frequent_value

b'1.5'