Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [29]:
import numpy as np

In [30]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
arr1d = np.array([1,2,3,4,5])
print(arr1d)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
# Write a NumPy function to create an array with random values of shape [3,4]
arr_rand = np.random.rand(3, 4)
print(arr_rand)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
arr_zeros = np.zeros((3, 4))
print(arr_zeros)

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
arr_ones = np.ones((3, 4))
print(arr_ones)


[[0.27474872 0.54854892 0.6863978  0.72862668]
 [0.04435207 0.48058072 0.20042825 0.47989157]
 [0.22421455 0.50506134 0.72748608 0.84529558]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
range_arr = np.arange(0, 10, 2)
print(range_arr)

# Hint : Use np.arange or np.linspace

[0 2 4 6 8]


### Basic array operations
- algebraic operations
- logical operations

In [33]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [34]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [35]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
print(np.sum(a, axis = 0))
# Write a NumPy function to get the sum of the array 'a' along axis=1
print(np.sum(a, axis = 1))

[ 6 17 14]
[10 13 14]


In [36]:
# Write a NumPy function to reverse the array 'a'
print(a[::-1, ::-1])
# Write a NumPy function to reverse the array 'a' along axis=0
print(a[::-1, :])
# Write a NumPy function to reverse the array 'a' along axis=1
print(a[:, ::-1])

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [37]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [38]:
# Write a NumPy function to sort the array 'a'
print(np.sort(a))
# Write a NumPy function to sort the array 'a' along axis=0
print(np.sort(a, axis = 0))
# Write a NumPy function to sort the array 'a' along axis=1
print(np.sort(a, axis = 1))
# Write a NumPy function to sort the array 'a' in descending order along axis=0
print(np.sort(a, axis = 0)[::-1, :])


[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [39]:
# Write a NumPy function to argsort the array along axis=0
print(np.argsort(a, axis = 0))
# Write a NumPy function to argsort the array along axis=1
print(np.argsort(a, axis = 1))

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [40]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
print(np.concatenate((a,b), axis = 0))
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
print(np.concatenate((a,b), axis = 1))
# Note: You can do the same function using stacking, discover and try that :)
print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8 11 16 18]
 [ 9  3  1 90 37 81]
 [ 1  8  5 61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8 11 16 18]
 [ 9  3  1 90 37 81]
 [ 1  8  5 61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [41]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [42]:
# Write a NumPy function to get the Number of dimensions
print(a.ndim)
# Write a NumPy function to get the Shape of the array
print(a.shape)
# Write a NumPy function to get the Size of the array
print(a.size)

2
(3, 3)
9


In [43]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
print(a.reshape(1,9))

[[4 6 8 9 3 1 1 8 5]]


In [44]:
# Write a NumPy function to add a new axis to the array 'a'
print(a[np.newaxis, :])
print(np.expand_dims(a, axis = 0))
# Note : Show atleast two different ways of doing this


[[[4 6 8]
  [9 3 1]
  [1 8 5]]]
[[[4 6 8]
  [9 3 1]
  [1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [45]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [46]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range


#Indexing by integer
print(a[1,2])

#Indexing by a tuple
print(a[1][2])

#Using range
print(a[0:2, 0:2])

1
1
[[4 6]
 [0 3]]


In [47]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
print(a[a>4])
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
print(a[(a>4) & (a%2 == 0)])

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [48]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [49]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
a_copy = np.copy(a)
a_new = a_copy + 1
print(a_new)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [50]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [51]:
import pandas as pd
df = pd.DataFrame(iris_2d, columns=['sepallength', 'sepalwidth', 'petallength', 'petalwidth'])


# Write a Pandas function to drop rows that contain a missing value.

df_clean = df.dropna()

In [52]:
# Write a Pandas function to find the correlation between the first two columns.
correlation = df[['sepallength','sepalwidth']].corr()
print(correlation)

             sepallength  sepalwidth
sepallength     1.000000   -0.109369
sepalwidth     -0.109369    1.000000


In [53]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
mean_val = df['petallength'].mean()
median_val = df['petallength'].median()
std_val = df['petallength'].std()
print(mean_val, median_val, std_val)

3.758666666666666 4.35 1.7644204199522617


In [54]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
df['volume'] = np.pi * df['petallength'] * df['sepallength'] ** 2

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [55]:
x = np.arange(4, dtype=np.int64)
ones = np.ones_like(x)
print(ones)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [56]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a, b, c = np.split(x, [4, 6])
print(a, b, c)

[1 2 3 4] [5 6] [7 8 9]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [57]:
x = np.random.randint(0, 10, (2, 5))
print("Array:\n", x)

max_values = np.max(x, axis=1)
min_values = np.min(x, axis=1)

max_indices = np.argmax(x, axis=1)
min_indices = np.argmin(x, axis=1)

print("Max values:", max_values)
print("Min values:", min_values)
print("Max indices:", max_indices)
print("Min indices:", min_indices)

Array:
 [[4 1 1 9 4]
 [4 5 6 3 5]]
Max values: [9 6]
Min values: [1 3]
Max indices: [3 2]
Min indices: [1 3]


### Pandas

Run the following load command and solve the following questions

In [58]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')



Q4 Write a Pandas function to find the count of unique species.

In [59]:
df = pd.DataFrame(iris, columns=names)


species_counts = df['species'].value_counts()
print(species_counts)

species
b'Iris-setosa'        50
b'Iris-versicolor'    50
b'Iris-virginica'     50
Name: count, dtype: int64


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [60]:
def bin_petal_length(petal_lengths):
    petal_lengths = petal_lengths.astype(float)
    bins = pd.cut(petal_lengths, bins=[-np.inf, 3, 5, np.inf], labels=['small', 'medium', 'large'])
    return bins

binned = bin_petal_length(df['petallength'])
print(binned)

0       small
1       small
2       small
3       small
4       small
        ...  
145     large
146    medium
147     large
148     large
149     large
Name: petallength, Length: 150, dtype: category
Categories (3, object): ['small' < 'medium' < 'large']


Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [61]:
most_frequent = pd.Series(df['petallength'].astype(float)).mode()[0]
print(most_frequent)

1.5
